apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: backstage-selfsigned
  namespace: backstage
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-tls
  namespace: backstage
spec:
  secretName: backstage-tls
  issuerRef:
    name: backstage-selfsigned
    kind: Issuer
  dnsNames:
    - backstage.127.0.0.1.nip.io
