apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-k-mesh
  namespace: argocd
spec:
  project: eventing
  source:
    repoURL: https://github.com/craigedmunds/argocd-eda.git
    path: kustomize/mesh
    kustomize:
      enableHelm: true
      buildOptions: "--enable-helm"
  # source:
  #   chart: camel-k
  #   repoURL: https://apache.github.io/camel-k/charts
  #   targetRevision: 2.8.0

  #   kustomize:
  #     patches:
  #     - patch: |-
  #         apiVersion: apps/v1
  #         kind: Deployment
  #         metadata:
  #           name: camel-k-operator
  #         spec:
  #           template:
  #             spec:
  #               containers:
  #               - name: camel-k-operator
  #                 env:
  #                   - name: WATCH_NAMESPACE
  #                     # todo : drive this from configuration
  #                     value: camel-k-mesh,camel-k-mesh-demo
  #                     valueFrom: null
      

  destination:
    server: https://kubernetes.default.svc
    namespace: camel-k-mesh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    # hooks:
    #   - type: PostSync
    #     command: ["helm"]
    #     args: ["dependency", "update"]