apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-k-operator
  namespace: argocd
spec:
  project: eventing
  source:
    repoURL: https://apache.github.io/camel-k/charts/
    targetRevision: 2.8.0
    chart: camel-k

  destination:
    server: https://kubernetes.default.svc
    namespace: camel-k
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
