apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    targetRevision: v1.19.1
    chart: cert-manager
    helm:
      parameters:
        - name: crds.enabled
          value: 'true'

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
