apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: camel-k-mesh-consumers
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/craigedmunds/argocd-eda.git
      revision: HEAD
      directories:
      - path: mesh/consumers/*
      values:
        consumer: "{{.path.basename}}"

  template:
    metadata:     
      name: 'camel-k-mesh-consumer-{{.values.consumer}}'

    spec:
      project: "eventing"
      source:
        repoURL: https://github.com/craigedmunds/argocd-eda.git
        targetRevision: HEAD
        path: 'mesh/consumers/{{.values.consumer}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: "camel-k-mesh-consumer-{{.values.consumer}}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true