---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "karavan"
  namespace: camel-karavan
stringData:
  karavan.keycloak.url: "https://karavan.127.0.0.1.nip.io"
  karavan.keycloak.realm: "karavan"
  karavan.keycloak.frontend.clientId: "karavan"
  karavan.keycloak.backend.clientId: "karavan"
  karavan.keycloak.backend.secret: "secret"
  karavan.git.repository: "http://github.com/craigedmunds/karavan.git"
  karavan.git.username: "karavan"
  karavan.git.password: "karavan"
  karavan.git.branch: "main"
  karavan.container-image.registry: "ghcr.io/craigedmunds"
  karavan.container-image.group: "karavan"
  karavan.container-image.registry-username: USERNAME
  karavan.container-image.registry-password: password
