{{- $lob := .Values.lob }}
{{- $service := .Values.name }}
{{- range $k, $v := .Values.channels }}
{{- $event := lower $k }}

apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: lob-{{$lob}}-{{$service}}-{{ $event }}
  namespace: camel-k-mesh
spec:
  name: ex.{{$lob}}.{{$service}}.{{ $event }}
  type: headers # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: camel-k-mesh

---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: lob-{{$lob}}-{{$service}}-sample-{{ $event }}
  namespace: camel-k-mesh
spec:
  name: q.{{$lob}}.{{$service}}.sample.{{ $event }} # name of the queue
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: camel-k-mesh

---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: lob-{{$lob}}-{{$service}}-sample-{{ $event }}-binding
  namespace: camel-k-mesh
spec:
  source: ex.{{$lob}}.{{$service}}.{{ $event }} # an existing exchange (the rabbit mq internal name)
  destination: q.{{$lob}}.{{$service}}.sample.{{ $event }} # an existing queue (the rabbit mq internal name)
  destinationType: queue # can be 'queue' or 'exchange'
  rabbitmqClusterReference:
    name: camel-k-mesh

{{- end }}