apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-component-camel-k-mesh
  namespace: backstage
data:

  catalog-component-camel-k-mesh.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Domain
    metadata:
      name: ecommerce
      description: The ecommerce domain
    spec:
      owner: crm
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Domain
    metadata:
      name: identity
      description: The ecommerce identity subdomain
    spec:
      owner: crm
      subdomainOf: ecommerce
    ---
    apiVersion: backstage.io/v1alpha1
    kind: System
    metadata:
      name: camel-k-mesh
      description: A POC event mesh system built with Camel-K
    spec:
      owner: apim
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: camel-k-mesh-rabbit-mq-cluster
      annotations:
        backstage.io/kubernetes-id: camel-k-mesh-rabbit-mq-cluster
    spec:
      type: service
      lifecycle: production
      owner: apim
      system: camel-k-mesh

  catalog-component-camel-k-mesh-sample.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: Domain
    metadata:
      name: sample
      description: The sample domain
    spec:
      owner: apim
    ---
    apiVersion: backstage.io/v1alpha1
    kind: System
    metadata:
      name: sample
      description: A sample system
    spec:
      owner: apim
      domain: sample
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: sample-service
      annotations:
        backstage.io/kubernetes-id: camel-k-mesh-sample
    spec:
      type: service
      lifecycle: production
      owner: apim
      system: sample
      providesApis:
        - sample-api
    ---
    apiVersion: backstage.io/v1alpha1
    kind: API
    metadata:
      name: sample-api
      description: Does stuff
    spec:
      type: openapi
      lifecycle: production
      owner: apim
      system: sample
      definition: |
        openapi: "3.0.0"
        info:
          version: 1.0.0
          title: Artist API
          license:
            name: MIT
        servers:
          - url: http://artist.spotify.net/v1
        paths:
          /artists:
            get:
              summary: List all artists