apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: camel-k-mesh-lob-applications
spec:
  template:
    spec:
      source:
        helm:
          parameters:
            - name: name
              value: '{{.path.basename}}'
            - name: argocd.lob_services.branch
              value: feature/branch-based
