apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: eventing
  source:
    repoURL: https://strimzi.io/charts/
    targetRevision: 0.46.0
    chart: strimzi-kafka-operator
    helm:
      parameters:
        - name: namespaced
          value: "false"
        - name: watchNamespaces
          value: "kafka"
        - name: rbac.create
          value: "true"
        - name: rbac.namespaced
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: strimzi-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
