apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eventing
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/craigedmunds/argocd-eda.git
    - https://github.com/craigedmunds/confluent-kubernetes-examples.git
    - https://packages.confluent.io/helm
    - https://prometheus-community.github.io/helm-charts
    - https://charts.bitnami.com/bitnami
    - https://apache.github.io/camel-k/charts/
    - https://backstage.github.io/charts
  sourceNamespaces: []
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # namespaceResourceBlacklist:
  # - group: '*'
  #   kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  namespaceResourceBlacklist:
  - group: '*'
    kind: '*'