apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camel-k-mesh
  namespace: argocd
spec:
  project: eventing
  source:
    repoURL: https://github.com/craigedmunds/argocd-eda.git
    path: kustomize/camel-k-mesh
    targetRevision: niv-test
  destination:
    server: https://kubernetes.default.svc
    namespace: camel-k-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
