apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-component-camel-k-mesh-demo-user-service
  namespace: backstage            # or your app ns; just mount it where Backstage runs
data:
  catalog-component-camel-k-mesh-demo-user-service.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: API
    metadata:
      name: {{.Values.lob}}-{{.Values.name}}
      description: Does stuff
    spec:
      type: asyncapi
      lifecycle: production
      owner: apim
      system: {{.Values.lob}}
      component: {{.Values.lob}}-{{.Values.name}}
      apiProvidedBy: {{.Values.lob}}
      definition: |
        openapi: "3.0.0"
        info:
          version: 1.0.0
          title: Artist API
          license:
            name: MIT
        servers:
          - url: http://artist.spotify.net/v1
        paths:
          /artists:
            get:
              summary: List all artists
