apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: lob-demo-user-service-usercreated
  namespace: camel-k-mesh
spec:
  name: ex.demo.user-service.usercreated
  type: headers # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: camel-k-mesh
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: lob-demo-user-service-usercreated-binding
  namespace: camel-k-mesh
spec:
  source: ex.demo.user-service.usercreated
  destination: q.my-simple-http-service.demo.user-service.usercreated
  destinationType: queue
  rabbitmqClusterReference:
    name: camel-k-mesh
